version: '3.8'

services:
  fastapi:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "ls -la && ls  && pwd &&  uvicorn app:app  --host 0.0.0.0 --reload"
    restart: always